<?php

/*
 * Display help Message
 */
function landing_page_creator_help($path, $arg) {
  switch ($path) {
    case "admin/help#landing_page_creator":
      return t("Create landing pages for assignment of DOIs");
      break;
  }
}

function landing_page_creator_page_attachments(array &$page) {
  //dpm(get_loaded_extensions());

  $page['#attached']['library'][] = 'landing_page_creator/landing_page_creator';
}
